on:
  workflow_dispatch:
    inputs:
        github:
          description: "github repo"
          required: true
          type: string
        binary:
          description: "binary name"
          required: true
          type: string
        buildcmd:
          description: "command to build"
          required: true
          type: string
          default: "go build"
        goos:
          description: "goos"
          required: true
          type: string
          default: "linux"
        goarch:
          description:  "goarch"
          required: true
          type: string
          default: "amd64"

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@master
      with:
        repository: ${{ github.event.inputs.github }}
        path: "buildp"
    - uses: actions/setup-go@v5
    - name:  build code
      env: 
        GOOS: ${{ github.event.inputs.goos }}
        GOARCH: ${{ github.event.inputs.goarch }}
      run: |
          cd  buildp
          echo "${{ github.event.inputs.buildcmd }}"
          ${{ github.event.inputs.buildcmd }}
    - run:  ls -lht ./buildp
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
          tag: abc
          files: |
            ./buildp/${{ github.event.inputs.binary  }}
    #- name:  upload artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #    path: ./buildp/${{ github.event.inputs.binary  }}
    #    retention-days: 4
